kurch_bakery/kurch_bakery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
]

kurch_bakery/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.orders_list, name='list'),
    path('order/<int:order_id>/', views.order_detail, name='detail'),
    path('order/create/', views.order_create, name='create'),
    path('order/<int:order_id>/remove/', views.order_remove, name='remove'),
    path('order/<int:order_id>/accept/', views.order_accept, name='accept'),
]

kurch_bakery/orders/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product

User = get_user_model()


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name='Время создания')
    started_date = models.DateTimeField(blank=True,
                                        verbose_name='Время начала')
    timeToCookTotal = models.DurationField(blank=True,
                                           verbose_name='Время приготовления')
    estimated_time = models.DurationField(default=timedelta(seconds=0),
                               verbose_name='Осталось времени')

    accepted = models.BooleanField(default=False,
                                   verbose_name='Принято в работу')
    finished = models.BooleanField(default=False,
                                   verbose_name='Заказ выполнен')

    products = models.ManyToManyField(
        Product,
        through='OrderRecord',
        through_fields=('order', 'product', 'quantity'))
    
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ('-created_date', )
    

class OrderRecord(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1,
                                                verbose_name='Количество')

    class Meta:
        verbose_name = 'Записи заказов'
        verbose_name_plural = 'Записи заказов'
        constraints = [
            models.UniqueConstraint(fields=['order', 'product'],
                                    name='order-elements')
        ]

kurch_bakery/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200)
    timeToCook = models.DurationField(
                        verbose_name='Время приготовления HH:MM:SS')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    
    def __str__(self):
        return self.name

kurch_bakery/orders/forms.py
from django import forms
from .models import OrderRecord
from django.contrib.auth import get_user_model


User = get_user_model()

class OrderRecordForm(forms.ModelForm):
    class Meta:
        model = OrderRecord
        fields = ('product', 'quantity')

kurch_bakery/orders/views.py
from datetime import datetime, timedelta
from django.urls import reverse
from django.utils.timezone import make_aware
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import (get_object_or_404, get_list_or_404, render,
                              redirect, HttpResponse)
from django.contrib.auth import get_user_model
from django.utils import timezone

from .models import OrderRecord, Order
from .forms import OrderRecordForm

# Наш список пользователей
User = get_user_model()

def calc_estimated_time():
    """ Вычисление оставшегося время и запись статуса в базу """
    orders = Order.objects.filter(accepted=True, finished=False)
    for order in orders:
        now = timezone.now()
        delta = now - order.started_date
        estimated_time = order.timeToCookTotal - delta
        if estimated_time.total_seconds() <= 0:
            estimated_time = timedelta(seconds=0)
            order.finished = True
        order.estimated_time = estimated_time
        order.save()
    

def orders_list(request):
    orders = Order.objects.select_related('owner')
    users = get_list_or_404(User)
    
    return render(request, 'orders/orders_list.html',
                  context={'orders': orders,
                           'users': users})


def order_detail(request, order_id):
    """ Детали заказа """
    form = OrderRecordForm(request.POST or None)
    order_content = None
    dt = None
    
    try:
        order_content = (OrderRecord.objects.select_related('product').
                         filter(order_id=order_id))
        dt = timedelta(seconds=calcCookTime_seconds(order_content))
    except ObjectDoesNotExist:
        pass

    if request.POST and form.is_valid():
        instance = form.save(commit=False)
        
        if order_content:
            for record in order_content:
                if (record.order.id == order_id and
                    record.product == instance.product):
                    instance.quantity += record.quantity

        OrderRecord.objects.update_or_create(order_id=order_id,
                                             product=instance.product,
                                             defaults={
                                                'quantity': instance.quantity})
        return redirect('orders:detail', order_id)
    order = get_object_or_404(Order, id=order_id)

    return render(request, 'orders/order_detail.html',
                  context={'order_content': order_content,
                           'timeToCookTotal': dt,
                           'form': form,
                           'order': order})


def order_create(request):
    """ Создание нового пустого заказа """
    uid = request.GET.get('uid')
    zero_time = timedelta(seconds=0)
    order = Order.objects.create(owner_id=uid,
                                 started_date=timezone.now(),
                                 timeToCookTotal=zero_time,
                                 estimated_time=zero_time)

    return redirect('orders:detail', order.id)


def add_product(request, order_id):
    """ Добавление продукта в заказ """
    form = OrderRecordForm(request.POST or None)

    if request.POST and form.is_valid():
        record = form.save(commit=False)

        record.order = get_object_or_404(Order, id=order_id)
        record.save()

    return render(request, 'orders/select_product.html', {'form': form})


def order_accept(request, order_id):
    """ Запуск заказа в исполнение """
    order = get_object_or_404(Order, id=order_id)
    try:
        order_content = OrderRecord.objects.filter(order=order)
        if not len(order_content):
            raise(ObjectDoesNotExist)
        timeToCookTotal = calcCookTime_seconds(order_content)
        order.timeToCookTotal = timedelta(seconds=timeToCookTotal)
        order.started_date = timezone.now()
        order.accepted = True
        order.save()

        # Чтобы сразу видеть остаток не дожидаясь планировщика
        calc_estimated_time()
        return redirect('orders:list')
    except ObjectDoesNotExist:
        return HttpResponse(f'Empty cart <a href="/order/{order_id}/">back<a>')



def order_remove(request, order_id):
    get_object_or_404(Order,id=order_id).delete()
    return redirect('orders:list')

def calcCookTime_seconds(order_content):
    """ Вычисляет время приготовления"""
    timeToCookTotal = 0

    for product in order_content:
        timeToCookTotal += (product.product.timeToCook.total_seconds() *
                            product.quantity)
    return timeToCookTotal

kurch_bakery/templates/includes/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>       
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

kurch_bakery/templates/includes/footer.html
<div>
    Sumenko V.    {% now "Y" %}
</div>

kurch_bakery/templates/includes/header.html
<div>
    Пекарня
</div>

kurch_bakery/templates/orders/order_detail.html
{% extends 'includes/base.html' %}
{% block content %}
    <div>
        <div>
            {% if order_content %}
                {% include 'orders/show_cart_content.html' %}
            {% else %}
                пусто
            {% endif %}
        </div>
        <div>
            {% if order.accepted %}
                accepted
            {% else %}
                {% include 'orders/select_product.html' with order=order form=form %}
                <a href="{% url 'orders:accept' order.id %}" >accept</a>
            {% endif %}
            <a href="{% url 'orders:list' %}">list orders</a>
        </div>
    </div>
{% endblock %}

kurch_bakery/templates/orders/orders_list.html
{% extends 'includes/base.html' %}
{% load template_filters %}
{% block content %}
    {% if orders %}
        <table border=1>
            <thead>
                <tr>
                    <th>#</th>
                    <th>personName</th>
                    <th>created date</th>
                    <th>accepted</th>
                    <th>finished</th>
                    <th>Estimated</th>
                    <th>do smth</th>
                </tr>
            </thead>
            <tbody>
                    {% for order in orders %}
                            <tr>
                                <td><a href='{% url 'orders:detail' order.id %}'>{{ order.id }}</a></td>
                                <td>{{ order.owner }}</td>
                                <td>{{ order.created_date|date:"Y-m-d h:i:s" }}</td>
                                <td>{{ order.accepted }}</td>
                                <td>{{ order.finished }}</td>
                                <td>{{ order.estimated_time|duration }}</td>
                                <td><a href="{% url 'orders:remove' order.id %}">remove</a></td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            {% else %}
            <div>
                <p>Нет заказов
            </div>
            {% endif %}
        {% include 'orders/select_person.html'%}
{% endblock %}

kurch_bakery/templates/orders/select_person.html
Create order for

<select name="persons" id="selectPerson" onchange="detectChange(this)">
    <option value="">--Select person--</option>
    {% for person in users %}
    <option id="select_{{ person.id }}" value="{{ person.id }}">{{ person.username }} </option>
    {% endfor %}
</select>
<a id="selectedPerson" href="">go</a>
<script>
    var link= document.getElementById('selectedPerson');
    document.getElementById("selectPerson").onchange = function(){
        var link = document.getElementById('selectedPerson');
        link.href="{% url 'orders:create' %}?uid=" + selectPerson.value;
    };
</script>

kurch_bakery/templates/orders/select_product.html
<form method="post" action="{% url 'orders:detail' order.id %}">
    {% csrf_token %}
    {% for field in form %}
        {{ field }}
    {% endfor %}
    <input type="submit" value="add">
</form> 

kurch_bakery/templates/orders/show_cart_content.html
<table border=1>
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Время приготовления</th>
            <th>Количество</th>
        </tr>
    </thead>
    <tbody>
            {% for record in order_content %}
                    <tr>
                        <td>{{ record.product }}</td>
                        <td>{{ record.product.timeToCook }}</td>
                        <td>{{ record.quantity }}</td>
                    </tr>
            {% endfor %}
            <tr>
                <td colspan="3">timeToCookTotal: {{ timeToCookTotal }}</td>
            </tr>
    </tbody>
</table>